<?php

if(isset($_SESSION['login'])){
	if(!$_SESSION['login']->esAdmin()) header("location:index.php");
	}
else header("location:index.php");
?>

<div id="administracion" class="container">
	  <?php require_once("vista_formulario_post.phtml");?>

<div style="margin-top: 20px" class="col-sm-10">
    <h3> ELIMINAR POSTS </h3>
    <hr>
    <?php 
      if(isset($lista_post)){
        echo "<div class='row'>";
            echo "<div  class='delAd col-sm-3'>";
              echo "<h4><b>Título</b></h4>";    
          echo "</div>";
          echo "<div class='col-sm-3'>";
              echo "<h4><b>Autor</b></h4>";    
          echo "</div>";
           echo "<div class='col-sm-3'>";
              echo "<h4><b>Fecha</b></h4>";    
          echo "</div>";
        echo "</div>";
        foreach ($lista_post as $p ) { 
        echo "<div style='margin-top:10px' class='row'>";
        //formulario oculto para editar post
        echo "<form action='index.php' method='POST'>";

          echo "<div class='delAdmin col-sm-3'>";  
              echo "<h5>". $p->getTitulo() ."</h5>"; 
              //echo "<input type='text' name='editaTitulo' value='".$p->getTitulo()."' required>";   
          echo "</div>";

          echo "<div class='delAdmin col-sm-3'>";
              echo $p->getAutor(); 
              //echo "<input type='text' name='editaTexto' value='".$p->getAutor()."' required>";    
          echo "</div>";

          echo "<div class='delAdmin col-sm-3'>";
              echo post::formateaFecha($p->getFecha());
              //echo "<input type='text' name='editaFecha' value='".$p->getFecha()."' required>";       
          echo "</div>";

          echo "<div class='col-sm-3'>";
            echo '<a href="index.php?admin&eliminaPost='.$p->getId().'"><span class="glyphicon glyphicon-trash"></span>Eliminar post</a>';
          echo "</div>";
 

          echo "</form>";
        echo "</div>";  

        }
      }
    ?>
</div>
<div style="margin-top: 20px" class="col-sm-10">
        <form action="index.php" method="post">
         <h3> AÑADIR PRODUCTO</h3><hr>

          <div class="form-group">
            <label for="nombreProducto">Nombre:</label>
            <input type="text" class="form-control" placeholder="Introduce el nombre del producto" name="nombreProducto" required>
          </div>

          <div class="form-group">
            <label for="precioProducto">Precio</label>
            <input type="number" step=".01" class="form-control" name="precioProducto" placeholder="Introduce el precio del producto" required>
          </div>
    
          <div class="form-group">
            <label for="categoriaProducto">Categoria</label>
          <input type="text" class="form-control" name="categoriaProducto" placeholder="Introduce la categoria del producto" required></input>
          </div>  
           
          <div class="form-group">  
          <label for="imagenProducto">Imagen</label>
          <input type="text" class="form-control" name="imagenProducto" placeholder="Introduce la url de la imagen del producto" required></input>
          </div> 
                
          <button type="submit" name="añadirProducto" class="btn btn-primary">Añadir producto</button>
        
    </div>


<div class="col-sm-10">                                                                                      
  <div class="table-responsive">
   <h3>ELIMINAR PRODUCTO</h3>           
  <table class="table">
    <thead>
      <tr>
        <th>Imagen</th>
        <th>Categoria</th>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Votos</th>
      </tr>
    </thead>
    <tbody>
      <?php
       if(isset($lista_productos)){
       
        foreach ($lista_productos as $pr ) { 
          
           echo '<tr>';
            echo '<td><img src="'.$pr->getImagen().'" width="100" height="100" class="img-responsive"></td>';
            echo '<td>'.$pr->getCategoria().'</td>';
            echo '<td>'.$pr->getNombre().'</td>';
            echo '<td>'.$pr->getPrecio().'€</td>';
            echo '<td>'.$pr->getVotos().'</td>';
            echo '<td><a href="index.php?admin&eliminaProducto='.$pr->getId().'"><span class="glyphicon glyphicon-trash"></span>Eliminar</a></td>';
          echo '</tr>'; 
          
        }
      }

      ?>
     
    </tbody>
  </table>
  </div>
</div>
</div>
</body>
</html>


</div>