


<div id="sobrenosotros">

<div id="about" class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-8">
      <h2>Sobre HardShopWare</h2><br>
      <br>
      <p>En 2018 nace HardShopWare y, desde el primer momento, apostamos por el canal online como nuestro principal foco de negocio. Este proyecto que hace años era todavía difícil de asimilar, por fin se pudo cumplir en la realidad.

      <p>Mantener el carácter del pequeño comercio, la cercanía con el cliente, el trato personalizado a los bloggers y consumidores de nuestra web son las premisas sobre las que gira nuestra filosofía. Seguiremos fieles a nuestros ideales hasta convertirnos en un referente web de venta/blog online de productos informáticos en España.</p>

      <p>Llegados a este punto, sólo podemos agradecer la confianza depositada en nosotros y el esfuerzo de toda la gente que ha pasado por aquí para hacer que HardShopWare sea una realidad y aspire a ser la tienda de informática basada en las reseñas de los clientes en España.</p>

    </div>
    <div id="iconoBarras" class="col-sm-4">
      <span class="glyphicon glyphicon-signal logo"></span>
    </div>
  </div>
</div>
<!-- Añadimos fondo gris a esta sección -->
<div class="container-fluid">
  <div class="row">
    <div id="iconoGlobo" class="col-sm-4">
      <span class="glyphicon glyphicon-globe logo"></span>
    </div>
    <div class="col-sm-8">
      <h2>Nuestros Valores</h2><br>
      <p><strong>MISIÓN:</strong> El espíritu por el que se crea HardShopWare es para poder ofrecer a todos los amantes de la tecnología las experiencias realmente importantes de los consumidores sobre los mejores componentes a precios asequibles, sin renunciar a la calidad</p><br>
      <p><strong>VISION:</strong> Nuestra visión es la de alcanzar el top de las tiendas online de informática con nuestra marca de identidad, las opiniones de los usuarios, de forma que nadie dude a qué portal acceder cuando quiera conocer las mejores opiniones sobre cualquier producto del mercado </p>
    </div>
  </div>
</div>



<div id="servicios" class="container-fluid text-center bg-grey">
  <h2>SERVICIOS</h2>
  <h4>Garantías de HardShopWare </h4>
  <br>
  <div class="row ">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-off logo-small"></span>
      <h4>Atención al cliente</h4>
      <p>No te guardes ninguna duda o pregunta sobre ese artículo que tanto te gusta. En nuestro Centro de Soporte estamos deseando poder ayudarte. ¡Pero qué majos somos!</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-heart logo-small"></span>
      <h4>Fácil navegación</h4>
      <p>Nuestra web ha sido diseñada atendiendo a las opiniones y sugerencias de personas como tú, que queréis una web sencilla, rápida y atractiva.</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-lock logo-small"></span>
      <h4>Compra segura</h4>
      <p>Paga de forma cómoda, rápida y segura en nuestra tienda. Utiliza el método de pago que más se adapte a ti, transferencia, ingreso, tarjeta o contrareembolso.</p>
    </div>
  </div>
  <br><br>
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-flash logo-small"></span>
      <h4>Contacto rápido</h4>
      <p>Nada más recibir nuestros emails de usuarios nos ponemos en marcha para resolver sus dudas o reclamaciones lo antes posible </p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-certificate logo-small"></span>
      <h4>Te escuchamos</h4>
      <p>Si tienes alguna sugerencia que podría ayudarnos a mejorar la experiencia de los usuarios y a seguir avanzando como portal web, no dudes en escribirnos. ¡Lo hacemos por tí!</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-leaf logo-small"></span>
      <h4 style="color:#303030;">Opiniones de todos</h4>
      <p>¿Alguna mala experiencia con algún producto? Si quieres recomendar algo a los demás usuarios o conocer sus opiniones, nuestra sección de blog está diseñada para ayudarte </p>
    </div>
  </div>
</div>

<div id="contacto">
 <div class="container-fluid">
  <h2 class="text-center">CONTACTO</h2>
  <div class="row">
    <div class="col-sm-5">
      <p>Contacta con nosotros y te responderemos en menos de 24 horas.</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> Granada, España</p>
      <p><span class="glyphicon glyphicon-phone"></span> 958978642</p>
      <p><span class="glyphicon glyphicon-envelope"></span> hardshopware@gmail.com</p> 
    </div>
    <div class="col-sm-7">
      <form action="index.php" method="POST">
      <div class="row">
        <div class="col-sm-6 form-group">
          <input class="form-control" name="nombreContacto" placeholder="Nombre" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" name="emailContacto" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" name="comentarioContacto" required placeholder="Comentario" rows="5"></textarea><br>
      <div class="row">
        <div class="col-sm-12 form-group">
          <button class="btn btn-primary pull-center" name="enviarContacto" type="submit">Enviar</button>
        </div>
      </div>
      </form> 
    </div>
  </div>
</div> 
</div>


</div>

