

<div id="formularioPost" class="container">
	<div class="col-sm-10">
<form action="index.php?blog" method="post">
	<h3> AÑADIR POST </h3><hr>
  <div class="form-group">
          <h4> Categoria </h4>
    <select id="selectCategoria" name="selectCategoria" class="selectpicker" required >
        <option value="">Seleccionar</option>
        <option value="Portatiles">Portatiles</option>
        <option value="Perifericos">Perifericos</option>
        <option value="Monitores">Monitores</option>
        <option value="Gaming">Gaming</option>
        <option value="Ordenadores">Ordenadores</option>
        <option value="Consolas">Consolas</option>
    </select>
  </div>  
  <div class="form-group">
    <label for="tituloAdmin">Título:</label>
    <input type="text" class="form-control" id="tituloAdmin" placeholder="Introduce el título del post" name="tituloAdmin" required>
  </div>
  <div class="form-group">
    <label for="fechaAdmin">Fecha</label>
    <input type="date" class="form-control" id="fechaAdmin" name="fechaAdmin" required>
  </div>
  	
  <div class="form-group">
  	<label for="textoAdmin">Post</label>
  <textarea class="form-control" rows="5" id="textoAdmin" name="textoAdmin" placeholder="Introduce tu post" required></textarea>
  </div>	

  <div class="form-group">
    <label for="votoAdmin">Voto</label>
    <input type="number" class="form-control" id="votoAdmin" name="votoAdmin" min="0" max="10" placeholder="Introduce tu voto" required>
  </div>

<input type="hidden" name="autorAdmin" id="autorAdmin" value="<?php echo $_SESSION['login']->getNombre();?>">

  <button type="submit" name="postearAdmin" class="btn btn-primary">POSTEAR</button>
</form>
</div>




</div>